// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-11fQBJDfTWWs1JrrHl9GLQ9LK3w71kA',
    appId: '1:390929854081:web:3a6d3accad8ea8acae6780',
    messagingSenderId: '390929854081',
    projectId: 'note-taker-e8a9c',
    authDomain: 'note-taker-e8a9c.firebaseapp.com',
    storageBucket: 'note-taker-e8a9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCTNNJj-awUOaWCe2bvO_9NW2uGeDG9Nc',
    appId: '1:390929854081:android:33593c7ed011d3f1ae6780',
    messagingSenderId: '390929854081',
    projectId: 'note-taker-e8a9c',
    storageBucket: 'note-taker-e8a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXq2kK9bLuupbVB20NV2ts8PCwynmCpSs',
    appId: '1:390929854081:ios:5a0858f9052c9c75ae6780',
    messagingSenderId: '390929854081',
    projectId: 'note-taker-e8a9c',
    storageBucket: 'note-taker-e8a9c.appspot.com',
    iosBundleId: 'com.example.notesTaker',
  );
}
